{
 "title": "Kafka",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total time spent discovering facts ( seconds )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "time_spent_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total discovered facts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "discovered_facts_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Topic Partition current offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of under replicated partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kafka_topic_partition_under_replicated_partition{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Kafka brokers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "kafka_brokers{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of replicas per topic/partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "kafka_topic_partition_replicas{}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}